---
abstract: 'Testing for HTTP services'
author:
  - 'Socialtext <socialtext@socialtext.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-HTTP
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Class::Field: 0
  Encode: 0
  Filter::Simple: 0
  LWP: 5.827
  LWP::UserAgent: 0
  Test::Builder::Module: 0
  Test::More: 0
  Text::Balanced: 0
version: 0.17
