--- #YAML:1.0
name:                Test-HTTP
version:             0.16
abstract:            Testing for HTTP services
license:             ~
author:              
    - Socialtext <socialtext@socialtext.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Class::Field:                  0
    Encode:                        0
    Filter::Simple:                0
    LWP:                           5.827
    LWP::UserAgent:                0
    Test::Builder::Module:         0
    Test::More:                    0
    Text::Balanced:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
